# Generated by Django 5.2.4 on 2025-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='field',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низький пріоритет'), ('Medium', 'Середній пріоритет'), ('High', 'Високий пріоритет')], default='Low', max_length=30, verbose_name='Приорітет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', "Обов'язково"), ('In_progres', 'В процесі'), ('Done', 'Виконано')], default='Low', max_length=30, verbose_name='Статус'),
        ),
    ]
